title: Well Architected lab and training for Partners 2022
description: >-
  Designed by cloud architects at Microsoft.
  Ask your local GPS team for more info and guidance.
github_username:  Microsoft
#markdown: GFM
theme: jekyll-theme-cayman
